version: '3'

services:
  web:
    build: .
    ports:
        - 8000:8000
    volumes:
    - '.:/Django'
    tty: True
    stdin_open:  True
    depends_on:
        - db
    links: 
        - db
    
  db:
    image: postgres:11
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'